apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dlt-adapter.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "dlt-adapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dlt-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dlt-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dlt-adapter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health 
              port: http 
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: http 
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          env:
            - name: "DEBUG"
              value: {{ .Values.env.DEBUG | quote }}
            - name: "PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.key }}
            - name: "DOME_EVENTS_CONTRACT_ADDRESS"
              value: {{ .Values.env.DOME_EVENTS_CONTRACT_ADDRESS | quote }}
            - name: "DOME_EVENTS_CONTRACT_ABI"
              value: {{ .Values.env.DOME_EVENTS_CONTRACT_ABI | quote }}
            - name: "DOME_PRODUCTION_BLOCK_NUMBER"
              value: {{ .Values.env.DOME_PRODUCTION_BLOCK_NUMBER | quote }}
            - name: "RPC_ADDRESS"
              value: {{ .Values.env.RPC_ADDRESS | quote }}
            - name: "ISS"
              value: {{ .Values.env.ISS | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
